### ISSUE TITLE
Requires newer sdk version

### ISSUE THREAD

**Issue by DoublezA** [rom1v/sndcpy#10]
I received this issue when trying to run the bat file

adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1780591467.tmp/base.apk (at Binary XML file line #7): **Requires newer sdk version #29 (current version is #28)]**

What must I do to sort this issue out?

**Comment by rom1v** [comment]
Sndcpy requires Android 10. The new playback capture API has been introduced in Android 10.
