### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by PROTIKMNDL** [rom1v/sndcpy#112]
D:\scrcpy-win64-v1.16>sndcpy
Waiting for device...
Performing Streamed Install
Success
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...
Playing audio...
The system cannot find the path specified.

**Comment by rom1v** [comment]
Duplicate of #60.
