### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by nonetrix** [rom1v/sndcpy#125]
**Environment**
 - OS: Manjaro KDE
 - scrcpy version: 1.0-1
 - installation method: aur
 - device model: Google Pixel 3a
 - Android version: 11

**Describe the bug**
Everything seems fine besides on the Linux side where I get this
```
VLC media player 3.0.12 Vetinari (revision 3.0.12-1-0-gd147bb5e7e)
[000055df482dd8d0] dummy interface: using the dummy interface module...
[00007fb4600015c0] main stream error: connection error: Connection refused
```

**Comment by aa-ko** [comment]
Did you read [the instructions](https://github.com/rom1v/sndcpy#run-the-app)?

> VLC may print this error message once:
> main stream error: connection error: Connection refused
> It is "expected", just ignore it.
