### ISSUE TITLE
Doesn't work on Redmi Note 9T with Android 10

### ISSUE THREAD

**Issue by barfin** [rom1v/sndcpy#126]
```
[barfin@Barfin-Linux ~]$ sndcpy
Waiting for device...
Performing Streamed Install
Success
28200
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...

VLC media player 3.0.12 Vetinari (revision 3.0.12-1-0-gd147bb5e7e)
[000055d125361ce0] dummy interface: using the dummy interface module...
[00007f43880015c0] main stream error: connection error: Connection refused
```

**Comment by pranshuthegamer** [comment]
enable usb debugging
and when you open sndcpy check your phone for a permission

**Comment by barfin** [comment]
> enable usb debugging
> and when you open sndcpy check your phone for a permission

as you can see it's enabled that's why sndcpy successfully installed the sndcpy app
```
Waiting for device...
Performing Streamed Install
Success
```

**Comment by pranshuthegamer** [comment]
since the phone refused to connect ... idk

**Comment by andersmmg** [comment]
I get the same output, but it works just fine, are you sure it's not working?

**Comment by barfin** [comment]
> I get the same output, but it works just fine, are you sure it's not working?

yes it's not working

**Comment by barfin** [comment]
[log.txt](https://github.com/rom1v/sndcpy/files/6831256/log.txt)
here is the debugging log
