### ISSUE TITLE
Does it work on M1 or Apple Silicon?

### ISSUE THREAD

**Issue by steliosaa** [rom1v/sndcpy#131]
Does it work on M1 or Apple Silicon?

**Comment by brendeltruevant** [comment]
yes it does although i'm not able to adjust the volume for some reason

**Comment by steliosaa** [comment]
Thank you!

Can you please specify your set-up?
Which Mac device do you have? Which MacOS version are you currently on?

**Comment by brendeltruevant** [comment]
![image](https://user-images.githubusercontent.com/78739817/118007347-fa647380-b343-11eb-89ee-a3f3ca07ba95.png)

**Comment by steliosaa** [comment]
Thank you!
