### ISSUE TITLE
Audio Does not Forward

### ISSUE THREAD

**Issue by Premjit0** [rom1v/sndcpy#141]
VLC is installed, scrcpy is running and when running sndcy, android audio does not forward to the wndow 10 pc

**Comment by adibpwd** [comment]
I also experienced the same thing, sndcpy is running but not sending audio to my xubuntu laptop, why is that?

![image](https://user-images.githubusercontent.com/54851209/195962757-54141d68-61e2-4bb8-a939-37b5a2048ad0.png)

**Comment by adibpwd** [comment]
> VLC is installed, scrcpy is running and when running sndcy, android audio does not forward to the wndow 10 pc

Please open again this issue
