### ISSUE TITLE
Not able to stream the audio neither with VLC nor with scrcpy

### ISSUE THREAD

**Issue by ShivamJoker** [rom1v/sndcpy#15]
Hello can you please help, I cloned the repo and ran the executable everything went fine but I wasn't able to hear anything when I played music on my phone.

```sh
❯ ./sndcpy
Waiting for device...
Performing Streamed Install
Success
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...

VLC media player 3.0.11 Vetinari (revision 3.0.11-0-gdc0c5ced72)
[00007fe1c911e6c0] dummy interface: using the dummy interface module...
```
I also opened scrcpy but nothing happened

I am using Xiaomi Poco F1 running Android 10

Thanks!

**Comment by ShivamJoker** [comment]
Okay it works with youtube but not with Ymusic

**Comment by rom1v** [comment]
> Okay it works with youtube but not with Ymusic

OK (https://github.com/rom1v/sndcpy/blob/master/README.md#apps-restrictions)
