### ISSUE TITLE
No audio played in PC

### ISSUE THREAD

**Issue by QuantumLiu** [rom1v/sndcpy#16]
I followed every step, but nothing played in PC, and it shows 'Waiting for connection'  at the phone. But the Android system told that the app is recoding voice.
At Pc, system show the VLC is runing but not voice played.

Android version:10
OS:MIUI 12
windows 10
```
C:\cprojects\scrcpy-win64-v1.13>adb connect 192.168.1.5
connected to 192.168.1.5:5555

C:\cprojects\scrcpy-win64-v1.13>sndcpy
Waiting for device...
Performing Streamed Install
Success
5555
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...
Playing audio...
```

EDIT:
While it seems works only for several APPs, I still haven't figured out the reson and which APPs worked for it ....

**Comment by rom1v** [comment]
> While it seems works only for several APPs, I still haven't figured out the reson and which APPs worked for it ....

https://github.com/rom1v/sndcpy#apps-restrictions
