### ISSUE TITLE
Cannot find path specified

### ISSUE THREAD

**Issue by PeterKW** [rom1v/sndcpy#160]
I am getting an error messgae on Windows PowerShell that I am not quite understanding?

```
.\sndcpy
Waiting for device...
Performing Streamed Install
Success
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...
Playing audio...
The system cannot find the path specified.
```

Any idea what I should try next to debug this?

**Comment by rom1v** [comment]
Where is your VLC installed? #5

**Comment by PeterKW** [comment]
Ah, thank you very much. I don't think VLC was installed which seemed to be the problem.  If I navigate to the install directory "$env:userprofile\sndcpy\sndcpy" then I can run sndcpy. Is there a way to add this as a environmental variable in windows so that if I type ./sndcpy into powershell it knows what to do?

.\sndcpy
.\sndcpy: The term '.\sndcpy' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by PeterKW** [comment]
Thanks @weariestDuet 

I don't think that is quite what I'm looking for.

> Environment variables
> The scripts sndcpy and sndcpy.bat use some default values which can be overridden by environment variables.
> 
> ADB: the full path to the adb executable
> VLC: the full path to the vlc executable
> SNDCPY_APK: the full path to sndcpy.apk
> SNDCPY_PORT: the local port to forward to communicate with the device

I think what I was looking for is a way of executing sndcpy in powershell. What I was looking for is a way of when I type 'sndcpy' into powershell, something like the following is executed: 'cd $env:userprofile\sndcpy\ | ./sndcpy'

**Comment by PeterKW** [comment]
If I put the following into my Microsoft.PowerShell_profile.ps1 PoweShell profile file it seems to work well. 

#https://stackoverflow.com/a/13371499
function Sndcpy {
  Set-Location $env:userprofile\sndcpy\
  ./sndcpy
}

Set-Item -Path alias:<sndcpy> -Value Sndcpy
