### ISSUE TITLE
Failed to install sndcpy.apk

### ISSUE THREAD

**Issue by rgonzga** [rom1v/sndcpy#161]
Hi,

I tried running sndcpy on a Samsung Galaxy Note 8 but the script failed while trying to install the apk. What does this error mean? Can it be corrected?

> Waiting for device...
> Performing Streamed Install
> adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl2115913537.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #28)]
> Uninstalling existing version first...
> 
> Exception occurred while executing:
> java.lang.IllegalArgumentException: Unknown package: com.rom1v.sndcpy
>         at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4675)
>         at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:25487)
>         at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:25493)
>         at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:21145)
>         at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:934)
>         at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
>         at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
>         at android.os.ShellCommand.exec(ShellCommand.java:103)
>         at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26029)
>         at android.os.Binder.shellCommand(Binder.java:642)
>         at android.os.Binder.onTransact(Binder.java:540)
>         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3145)
>         at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4758)
>         at android.os.Binder.execTransact(Binder.java:739)
> Failed with error #255.

**Comment by rom1v** [comment]
> INSTALL_FAILED_OLDER_SDK

Sndcpy requires Android 10.
