### ISSUE TITLE
Forward audio from computer to phone?

### ISSUE THREAD

**Issue by adast9** [rom1v/sndcpy#173]
I was just wondering if this is possible? Basically reverse the default functionality.

**Comment by gregsskyles** [comment]
If I had to hazard a guess, no, this software isn't going to work for that.

Just thinking aloud here, VLC is available for Android and iOS, and can receive 'network streams.' If you had something running on the computer that could send the sound as such a network stream, then that would solve your problem. VLC itself can also send these streams; it wasn't clear in a quick look at the docs if you could get it to send the audio generally playing on the computer though.

**Comment by gregsskyles** [comment]
FWIW, I've been playing around with [AudioRelay](https://audiorelay.net/) and finding that it works pretty well with my phone and PC. YMMV.
