### ISSUE TITLE
sndcpy.bat closing almost immediately by itself

### ISSUE THREAD

**Issue by pompompuff** [rom1v/sndcpy#189]
hello ! i got scrcpy working fine , and now i'm trying to get sndcpy to work , but i always end up running into a new issue ...
currently , when i open the scrcpy.bat file, it shows this: ( i cant paste the code since it closes so fast )
![image](https://user-images.githubusercontent.com/95947523/145659279-d27de815-4e58-40c1-b28b-ea8f7d97054a.png)

here's a transcription of what it says:
```
Waiting for device...
Performing Streamed Install
Success
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }

Awaiting 2 seconds, press a key to continue...
```
( translated the last line so you can understand what it says , since my pc is in portuguese )
after that message, it simply closes by itself
it also never asks for permission to capture what's on my phone
i'm using a POCO X3 NFC ( it's a xiaomi ) and my computer runs on windows 10
i've already tried reinstalling sndcpy but it didn't solve anything
i have vlc installed and have already changed the sndcpy.bat to have its correct directory
my phone has all debugging permissions allowed and the installing apps through usb is allowed too, and i already have sndcpy on my phone
i cant find absolutely anything about this, please help ! :(

**Comment by jose94752** [comment]
Check Vlc.exe and his path in your computer and sndcpy.bat

**Comment by pompompuff** [comment]
> Check Vlc.exe and his path on your computer and sndcpy.bat

i already changed sndcpy.bat to have the correct path to vlc ! i copied it directly from the file explorer and stuff

**Comment by rom1v** [comment]
Start sndcpy.exe from a console, and read the error message.

If you don't know how to do that, read the FAQ from scrcpy: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by pompompuff** [comment]
> 
hiii thank you so much !!! after doing that i was able to solve it by doing some more searching
this showed up:
```
Waiting for device...
Performing Streamed Install
Success
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }

Aguardando 0 segundos, pressione uma tecla para continuar ...
Playing audio...
'"C:\Program Files (x86)\VideoLAN\VLC"' is not recognized as an internal or external command, operable program or batch file
```
turns out what i had to do was just type \vlc.exe in the directory ( C:\Program Files (x86)\VideoLAN\VLC\vlc.exe ) ! i thought i didnt have to do that since when i got the original file it didnt have it ? but then i searched online about the error and i had to tell the program to actually run the .exe file
i feel a little stupid now haha but im glad it worked !!! thank u sm for pointing me in the right direction ^__^
