### ISSUE TITLE
Support for Huawei P30 Pro

### ISSUE THREAD

**Issue by AruArshad** [rom1v/sndcpy#21]
![Screenshot from 2020-07-05 15-54-32](https://user-images.githubusercontent.com/25342570/86530672-333bec80-bed8-11ea-843c-9d597ecbcae0.png)

**Comment by rom1v** [comment]
Please post text instead of a screenshot of a terminal.

Is sndcpy.apk in that directory? What is the result of `ls`?

**Comment by AruArshad** [comment]
Yes. It's in that directory

**Comment by AruArshad** [comment]
its working now
