### ISSUE TITLE
Sncpy need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS 

### ISSUE THREAD

**Issue by Ventunesimo** [rom1v/sndcpy#216]
Hi guys! I receive this message when I try to run sndcpy on my Windows 10 connected to a Xiaomi Mi10T (scrcpy already work btw):

Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk:
Exception occurred while executing 'install':
java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:663)
        at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:536)
        at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCUninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]
Failed with error #1.

So, I tried to remove "-g" from the line code 15 in sndcpy.bat as someone suggested but iI just receive this:

Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
Uninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]
Failed with error #1.

I'm stuck, what have I to do to make It works? Again, scrcpy is working.
Thank you in advance for your help.

**Comment by rom1v** [comment]
#39
