### ISSUE TITLE
Language/unicode

### ISSUE THREAD

**Issue by lynrayy** [rom1v/sndcpy#217]
Can't change keyboard language from english to russian. When i trying to type, it typing english letters and sending errors to console 
![image](https://user-images.githubusercontent.com/59417884/159812173-2bec91cc-221a-4d5b-970c-6c97e1d3dfa2.png)

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#special-characters-do-not-work

(and this repo is sndcpy, not scrcpy)
