### ISSUE TITLE
adb failed to install sndcpy.apk Failure [INSTALL_FAILED_OLDER_SDK: Failed during installPackageLI

### ISSUE THREAD

**Issue by Putra3340** [rom1v/sndcpy#228]
??
![unknown](https://user-images.githubusercontent.com/95592362/175018932-892ef3b0-2d96-48e9-9cee-2d762326046d.png)

**Comment by rom1v** [comment]
sndcpy requires Android 10.

**Comment by Putra3340** [comment]
im using android 11
