### ISSUE TITLE
Have sndcpy not stop when the playlist ends

### ISSUE THREAD

**Issue by TheHighGroundWins** [rom1v/sndcpy#232]
I get that this feature is quite useful to exit the program for when the playlist ends, but its annoying for when the playlist is on loop and repeats.
Maybe add a toggle like a parameter when launching the program in the terminal.

**Comment by bwanapete** [comment]
I had similar frustrations but coming across this video from Shaad Razvi https://youtu.be/EH1GrmGLVk8 all my issues were solved with simple actions.
