### ISSUE TITLE
[advice] Change /opt to /usr/share

### ISSUE THREAD

**Issue by Freed-Wu** [rom1v/sndcpy#247]
After installation, I found

```sh
❯ pacman -Ql sndcpy
sndcpy-bin /opt/
sndcpy-bin /opt/sndcpy/
sndcpy-bin /opt/sndcpy/sndcpy
sndcpy-bin /opt/sndcpy/sndcpy.apk
sndcpy-bin /usr/
sndcpy-bin /usr/bin/
sndcpy-bin /usr/bin/sndcpy
sndcpy-bin /usr/share/
sndcpy-bin /usr/share/licenses/
sndcpy-bin /usr/share/licenses/sndcpy/
sndcpy-bin /usr/share/licenses/sndcpy/LICENSE
```

`/usr/bin/sndcpy` is only a shell to call `/opt/sndcpy`. Why not move `/opt/sndcpy/sndcpy` to `/usr/bin/sndcpy`
and move `/opt/sndcpy` to `/usr/share/sndcpy`? Thanks.

**Comment by rom1v** [comment]
I'm not responsible of the AUR package. Please report/ask to the maintainer: https://aur.archlinux.org/packages/sndcpy-bin

**Comment by Freed-Wu** [comment]
Thanks, I'll report.
