### ISSUE TITLE
Request To Make SoundCopy (sndcpy) work with Android 9 or older versions of Android

### ISSUE THREAD

**Issue by NAZIBULHAQUENAKIB** [rom1v/sndcpy#25]
I love using Scrcpy for the video. I use it with the highest quality, bitrate and other settings. It would be even better if it had an option to transmit sound via USB. But, It fortunatly doesn't have one 😥. I have a Samsung Galaxy S8+ with android version 9 which is not supported by SoundCopy or sndcpy. I tried building the app, changing sdk version and other stuff but couldn't make it work with Android 9. I thought about upgrading to Android 10( which might kill my phone slowly). I request Github to make sndcpy available for Android 9 or older. Please, Do it for the sake of poor guys like me 😥

**Comment by rom1v** [comment]
This is not possible, the API it uses has been introduced in Android 10.

**Comment by NAZIBULHAQUENAKIB** [comment]
I have seen you the significant improvement you guys have made in Screen
Copy from Version 1 to 1.14. If you guys try, I think you can find
something. There are apps like SoundWire and such which can transfer audio
wirelessly. Try something like that with SoundCopy

**Comment by NAZIBULHAQUENAKIB** [comment]
No problem. I will use Aux to record my gameplay but I want help to record
the screen of my Android directly with Scrcpy. I use this command: scrcpy
--record file.mp4 but I dont know in which path the video file is saved.
Please help🥺
