### ISSUE TITLE
Major bug/issue.

### ISSUE THREAD

**Issue by hackevil** [rom1v/sndcpy#26]
So first time i tried your program it was working fine, but after some time it uninstalled itself, i don't know why its happen, now after that i tried to install it it again by running the bat file by cmd it gives this error(see screenshot.1),
![Capture4](https://user-images.githubusercontent.com/23115256/87243453-c4204400-c453-11ea-88c9-deb60a914a7e.PNG)

 now after revoking usb debugging auth and deleting the ".android" folder i tried once and then i gave me this error( see screen shot.2).
![Capture5](https://user-images.githubusercontent.com/23115256/87243461-ca162500-c453-11ea-9d5f-8098ddf6d461.PNG)

 please help me with this.

**Comment by flyingduck234** [comment]
try updating adb to the latest
