### ISSUE TITLE
Android 14, Pixel 6, Sound drops on phone call

### ISSUE THREAD

**Issue by ThePowerTool** [rom1v/sndcpy#278]
Hi,

I'm on a Pixel 6 with Android 14.

I am running sndcpy via CL on my Fedora 40 computer.

I launch sndcpy and get sound through my headset connected to my computer, as expected.

Opening the phone and pressing numbers I hear DTMF.

The moment a call connects my headset has no sound and sound resumes on my phone.  I hit control-C after closing my phone (which is displayed, below).

Here is what appears on the command prompt:
guest@host:~/git/sndcpy$ ./sndcpy
Waiting for device...
Performing Streamed Install
Success
28200
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Playing audio...
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[000055e1d093e080] dummy interface: using the dummy interface module...
[00007f3d98000c90] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 0 ms)
^C[000055e1d08bbd70] main playlist: end of playlist, exiting

I would really love to use sndcpy.  Can you please, please help?

**Comment by rom1v** [comment]
> I'm on a Pixel 6 with Android 14.

> I am running sndcpy via CL on my Fedora 40 computer.

> I launch sndcpy and get sound through my headset connected to my computer, as expected.

You should use scrcpy instead :wink: 

> The moment a call connects my headset has no sound and sound resumes on my phone.

In any case, you could not forward audio for a call.

**Comment by ThePowerTool** [comment]
I am using scrcpy!

Thank you for letting me know the phone audio will not work. :( :( :(

I found sndcpy because of scrcpy.

I guess I'm just stuck using KDE Connect for audio.  It works for calls.

**Comment by ThePowerTool** [comment]
Follow-up update:
For anyone that finds this:  Bluetooth supports audio sinking to another device (including a PC).  I got it working using BT and going through the installation instructions and the GS Connect wiki repeatedly and following a recommendation from another forum where people were getting results by toggling BT off-then-on after changing settings[s].

I am now able to use scrcpy (and GS Connect / KDE Connect) at the same time while using my PC headset for telephone calls (and any other audio).

I really, really love how scrcpy puts my phone on my Linux Gnome desktop and then provides full access to my phone's UI as well as audio via my PC headset.  I can leave my phone on the charger when I am at my desk and solely focus on my PC desktop.
