### ISSUE TITLE
Lag when using sndcpy

### ISSUE THREAD

**Issue by slimsymphony** [rom1v/sndcpy#3]
Thanks to @rom1v :)  
Testing on macos with Pixel 2XL and the feature works fine.
But the lag is quite obvious , around 3-5 seconds.
Just want to know any suggestion  to decrease the lag, or any plan to improve it?

**Comment by rom1v** [comment]
Over USB?

In your console, do you see logs similar to:
>     main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 377 ms)

https://github.com/rom1v/sndcpy#audio-delay

**Comment by slimsymphony** [comment]
well，it's through tcp... 
Connected with a remote device. I will check the parameters and try to find a proper value.
Thanks.
