### ISSUE TITLE
Requires newer sdk version #29 (current version is #24)

### ISSUE THREAD

**Issue by bl4ckck** [rom1v/sndcpy#37]
```
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl33316899.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #24)]
Uninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]
Performing Streamed Install
adb: failed to install sndcpy.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1606743385.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #24)]
Failed with error #1.
Press any key to continue . . .
```

**Comment by rom1v** [comment]
Yes, it requires Android 10, and may not work on older versions.

**Comment by biancashouse** [comment]
Does this mean only real devices having Android 10 or later will be able to download your app ?

**Comment by rom1v** [comment]
Yes.

**Comment by Proryanator** [comment]
Was there any Android SDK library before 10 that would support audio capture?

Or a way to use intermediary file I/O to achieve the same kind of streaming functionality on an older Android device?

I'm looking into doing what you have here for the Oculus Quest, which is on API 25.

**Comment by ghaly854** [comment]
مرحبا انا لدي مشكله أنه عندما اشغل البرنامج على الكمبيوتر يحذف التطبيق من الهاتف ويقول لي الاصدار الحالي 28 واصدارك 29

**Comment by DiogoRosado96** [comment]
> So I guest it's because I have Android 9 ?? `Requires newer sdk version #29 (current version is #28)]`

Yes! sdk 28 is for Android 9 and SDK29 is for Android 10
