### ISSUE TITLE
Hi. I couldn't work on My K20 pro and windows 10 pc. Please help

### ISSUE THREAD

**Issue by Vishnudasnb** [rom1v/sndcpy#39]
Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:542)
        at com.android.server.pm.PackageInstallerService.createSession(PackageUninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]
Failed with error #1.
Press any key to continue . . .

![Screenshot (4)](https://user-images.githubusercontent.com/50900593/88719078-56a53080-d140-11ea-8145-fdd190500676.png)
 This is the error i get. Can You please help me out with this?

**Comment by rom1v** [comment]
It seems that your device ROM does not give the expected permissions to shell (probably modified by the vendor).

As a workaround, remove `-g` here:

https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L15

**Comment by Vishnudasnb** [comment]
hi 
i get this message below


Waiting for device...
1763 KB/s (91689 bytes in 0.050s)
Success
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...







when i press ender the cmd closes can you help me?

**Comment by Vishnudasnb** [comment]
It's okay bro I changed the enviormental variable and its working fine now. Thank you for this bro. you made my life keep up the good work and thank you so much.

**Comment by DiSavi** [comment]
> It seems that your device ROM does not give the expected permissions to shell (probably modified by the vendor).
> 
> As a workaround, remove `-g` here:
> 
> https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L15

should that be copied when you start the cmd or what

**Comment by DiSavi** [comment]
![image](https://user-images.githubusercontent.com/74814477/99975940-20e91f00-2da3-11eb-8874-8a81bf727cc1.png)

**Comment by rom1v** [comment]
Did you press Enter in the console?

**Comment by DiSavi** [comment]
I did.. its just gone.. nothing happens Sent from Mail for Windows 10 From: Romain VimontSent: Monday, November 23, 2020 4:09 PMTo: rom1v/sndcpyCc: DiSavi; CommentSubject: Re: [rom1v/sndcpy] java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS (#39) Did you press Enter in the console?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DiSavi** [comment]
> Did you press Enter in the console?

i did.. nothing happens.. console disappear

**Comment by rom1v** [comment]
> i did.. nothing happens.. console disappear

Do you have VLC installed at the correct location? #5

**Comment by DiSavi** [comment]
> > i did.. nothing happens.. console disappear
> 
> Do you have VLC installed at the correct location? #5

yes sir

**Comment by rom1v** [comment]
If it closes immediately, then it can't start VLC for some reason.

**Comment by DiSavi** [comment]
> If it closes immediately, then it can't start VLC for some reason.
> 
> Open a terminal (Win+r, `cmd.exe`), `cd C:\........\sndcpy`, and execute `sndcpy.bat` (it will not close the terminal and show the error message).

do i need VLC in same folder as snd? or what.. you need to simple thing not to confuse me more mate

**Comment by rom1v** [comment]
Please read #5.

**Comment by DiSavi** [comment]
> Please read #5.

can you just send me the correct bat thingy so we could all live in peace

**Comment by EzzPrograms** [comment]
> can you just send me the correct bat thingy so we could all live in peace  

The main reason why rom1v asked you to do this is to actually pinpoint where the problem is.
There's no such thing as the perfect/correct bat file that can actually work with every single problem that is unique to each user.

> If it closes immediately, then it can't start VLC for some reason.
> 
> Open a terminal (Win+r, cmd.exe), cd C:\........\sndcpy, and execute sndcpy.bat (it will not close the terminal and show the error message).

This is called a "troubleshooting step", so we know what exactly your problem is and we can do the solution for that problem.
Every problem has a different solution, so if you would just let us know what this produces, then we could help a little bit more to as what the problem is at hand.

**Comment by DiSavi** [comment]
> > can you just send me the correct bat thingy so we could all live in peace
> 
> The main reason why rom1v asked you to do this is to actually pinpoint where the problem is.
> There's no such thing as the perfect/correct bat file that can actually work with every single problem that is unique to each user.
> 
> > If it closes immediately, then it can't start VLC for some reason.
> > Open a terminal (Win+r, cmd.exe), cd C:........\sndcpy, and execute sndcpy.bat (it will not close the terminal and show the error message).
> 
> This is called a "troubleshooting step", so we know what exactly your problem is and we can find the solution for that problem.
> Every problem has a different solution, so if you would just let us know what this outputs, then we could help a little bit more to as what the problem is at hand.

bruh, when i connect that snd thingy it outputs nothing.. it should give a sound on my pc right? or im wrong

**Comment by EzzPrograms** [comment]
> bruh, when i connect that snd thingy it outputs nothing.. it should give a sound on my pc right? or im wrong

Copy the text from the command prompt, it should show you something.
This is a visual step on how I can get the output log: https://v.ezz.moe/1124/17-20-53.mp4
What we want is what's gonna be shown here: https://img.ezz.moe/1124/17-28-17.png
You can copy the text from there or take a screenshot of it.
**Open a terminal first** (Windows Key + R, "cmd" in the Run window) to make sure the window doesn't close when it fails.

**Comment by DiSavi** [comment]
![image](https://user-images.githubusercontent.com/74814477/100077657-e8991d80-2e42-11eb-96a6-41b11bf37544.png)


> > bruh, when i connect that snd thingy it outputs nothing.. it should give a sound on my pc right? or im wrong
> 
> Copy the text from the command prompt, it should show you something.
> This is a visual step on how I can get the output log: https://v.ezz.moe/1124/17-20-53.mp4
> What we want is what's gonna be shown here: https://img.ezz.moe/1124/17-28-17.png
> You can copy the text from there or take a screenshot of it.
> **Open a terminal first** (Windows Key + R, "cmd" in the Run window) to make sure the window doesn't close when it fails.

![image](https://user-images.githubusercontent.com/74814477/100077681-ef279500-2e42-11eb-834d-9a718d9f1a8b.png)

**Comment by DiSavi** [comment]
dude dude dude.. i made it.. works.. just have a minor delay..

**Comment by rom1v** [comment]
> just have a minor delay..

Edit the `.bat` with this change (replace `50` by `0`):
https://github.com/rom1v/sndcpy/commit/39bd8c74485cf6dd4f34d58b94ea4f1e8fbccacf

**Comment by DiSavi** [comment]
> > just have a minor delay..
> 
> Edit the `.bat` with this change (replace `50` by `0`): [39bd8c7](https://github.com/rom1v/sndcpy/commit/39bd8c74485cf6dd4f34d58b94ea4f1e8fbccacf)

thanks a bunch friend.. you the best guys

**Comment by jhonathannc** [comment]
> It seems that your device ROM does not give the expected permissions to shell (probably modified by the vendor).
> 
> As a workaround, remove `-g` here:
> 
> https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L15

I had to remove it on line 18 as well. It worked for me.
https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L18

**Comment by Nungki1999** [comment]
> It seems that your device ROM does not give the expected permissions to shell (probably modified by the vendor).
> 
> As a workaround, remove `-g` here:
> 
> https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L15

I have followed the steps but still, no change

**Comment by qwertyuiop251** [comment]
> It seems that your device ROM does not give the expected permissions to shell (probably modified by the vendor).
> 
> As a workaround, remove `-g` here:
> 
> https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L15

Where to find the file? i also have this problem

**Comment by rom1v** [comment]
It's `sndcpy.bat` in the release.

**Comment by qwertyuiop251** [comment]
do i need to download the files? i only downloaded the sndcpy-with-adb

**Comment by rom1v** [comment]
It's in the archive `sndcpy-with-adb.zip`.

**Comment by qwertyuiop251** [comment]
sorry, i don't understand.
i downloaded the file and it contains 

adb 
AdbWinApi.dll
AdbWinUsbApi.dll
sndcpy
sndcpy
sndcpy 

for the first installation open the sndcpy file that is windows batch file right?

**Comment by rom1v** [comment]
The filenames have extensions, it's just that Windows by default hides them.

Random link to unhide them: https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/

**Comment by qwertyuiop251** [comment]
> The filenames have extensions, it's just that Windows by default hides them.
> 
> Random link to unhide them: https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/

ok i've installed them
now after i clicked and authorized from my phone i need to click enter, but after i did that there's no sound coming through..

> The filenames have extensions, it's just that Windows by default hides them.
> 
> Random link to unhide them: https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/

Thanks! got it working after following ur guide up top where the sndcpy.bat cannot find the vlc.exe just need to change the address and it works. again thank you

**Comment by rivldy** [comment]
![image](https://user-images.githubusercontent.com/65071107/144725937-35adcb2b-0073-4182-89ed-7758a95a992c.png)

Any solution?, I didn't cancel anything.

**Comment by rom1v** [comment]
@rivldy #64 (and please don't post screenshot of text, just post the text as text in a code block with ```)

**Comment by raaron773** [comment]
Having this same issue on Linux.
I am not sure how it differs compared to windows 10 but I tried removing `-g` from sndcpy.bat on line 15 and even tried commenting out line 18 like mentioned. It did not work. After digging a bit deeper there was something about enabling "install via USB" but this option is not available on OnePlus Nord 2. I am not sure what else I am missing.

**Comment by AzharArzk** [comment]
@raaron773 can i look your code sndcpy, i have same issue in linux

**Comment by raaron773** [comment]
> @raaron773 can i look your code sndcpy, i have same issue in linux

Sure
```
set -e
ADB=${ADB:-adb}
VLC=${VLC:-vlc}
SNDCPY_APK=${SNDCPY_APK:-sndcpy.apk}
SNDCPY_PORT=${SNDCPY_PORT:-28200}

serial=
if [[ $# -ge 1 ]]
then
    serial="-s $1"
    echo "Waiting for device $1..."
else
    echo 'Waiting for device...'
fi

"$ADB" $serial wait-for-device
"$ADB" $serial install -t -r "$SNDCPY_APK" ||
{
    echo 'Uninstalling existing version first...'
    "$ADB" $serial uninstall com.rom1v.sndcpy
    "$ADB" $serial install -t "$SNDCPY_APK"
}

"$ADB" $serial shell appops set com.rom1v.sndcpy PROJECT_MEDIA allow
"$ADB" $serial forward tcp:$SNDCPY_PORT localabstract:sndcpy
"$ADB" $serial shell am start com.rom1v.sndcpy/.MainActivity

sleep 2

echo Playing audio...
"$VLC" -Idummy --demux rawaud --network-caching=0 --play-and-exit tcp://localhost:"$SNDCPY_PORT"

```
That about it. I only removed the -g so.. It still isn't working. Kind of frustrating tbh

**Comment by Denis50921** [comment]
Hi a have problem,only audio,but i need see screen
![изображение](https://user-images.githubusercontent.com/107351533/230105028-56719782-5b21-43b9-be39-59c948da512d.png)
