### ISSUE TITLE
Can't install  sndcpy.apk

### ISSUE THREAD

**Issue by cctyl** [rom1v/sndcpy#43]
First, I try install from adb，it show 
![Snipaste_2020-08-11_22-03-25](https://user-images.githubusercontent.com/34262992/89906952-9418bc00-dc1e-11ea-975b-dbfb162fbfbb.png)

Then，i cry copy this apk to Android，also failed

![Snipaste_2020-08-11_22-06-15](https://user-images.githubusercontent.com/34262992/89907252-0093bb00-dc1f-11ea-91a7-0d890dc4cce6.png)
my phone sdk version is Android 7.1 25 Nougat

**Comment by rom1v** [comment]
> The Android device requires at least Android 10.

https://github.com/rom1v/sndcpy#requirements

**Comment by cctyl** [comment]
i am sorry
