### ISSUE TITLE
Android 9 support will be awesome-with zoom call sound forward

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [rom1v/sndcpy#45]
Hi Dude,

Could you please do for Android 9. You can help many, if you can support Android 9 with zoom sound forward. Thanks! Do you have any plan?

**Comment by rom1v** [comment]
No, the API has been introduced in Android 10.

You could use a Jack cable if your device supports it, or you could try https://github.com/rom1v/usbaudio (but it will probably not work on Android 9).

**Comment by vijayakumarmariyappan** [comment]
Thanks dude 👍
