### ISSUE TITLE
Doesn't work on Xiaomi Mi 9t (MIUI Global 12.0.3) and Windows 10 (2004)

### ISSUE THREAD

**Issue by AlexTCGPro** [rom1v/sndcpy#46]
Hey.
I followed the guide.
Mi phone is connected via USB with debug mode enabled. I then start sndcpy.bat either by itself or by cmd.
It's always stuck on "Waiting for device..."

I tried every option when connecting the phone to the computer. Enabling all debugging options in the developer menu. Disabling MIUI optimizations. Changing cable and usb ports. Makes no difference.

VLC is correctly installed but I had to change the folder in the bat file as it pointed to the 64bit variant but I have the 32bit one.

**Comment by rom1v** [comment]
Does `adb devices` shows your device?

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#device-not-detected

**Comment by AlexTCGPro** [comment]
I just ran adb.exe through cmd with the commant get-state. No device is found

**Comment by rom1v** [comment]
That's the problem then. Try to install the drivers (see previous link).

**Comment by AlexTCGPro** [comment]
Well, tried to update drivers from multiple sources, including oem.
Sadly, the problem persist.

No device is ever found.

**Comment by rom1v** [comment]
Check on stackoverflow how to make your specific device detected by adb.

**Comment by AlexTCGPro** [comment]
I have an update.
I just tried the Vysor app, which too mirrors the phone in a very similar way.

It does detect the phone, asks for debugging permission and can install its app from the computer.
Doesn't seem to be a driver problem after all. It must be something with adb as you say

**Comment by AlexTCGPro** [comment]
Replaced sndcpy adb files with theirs. They were different.
It succesfully detects the phone.
But brings out this error:

Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:542)
        at com.android.server.pm.PackageInstallerService.createSession(PackageUninstalling existing version first...
Success
Performing Streamed Install
adb: failed to install sndcpy.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:542)
        at com.android.server.pm.PackageInstallerService.createSession(PackageFailed with error #1.

**Comment by rom1v** [comment]
> Replaced sndcpy adb files with theirs. They were different.

What is the result of `adb --version`?

>     java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

See #39

**Comment by AlexTCGPro** [comment]
Just downloaded adb files directly from google servers, they appear to be the same as the Vysor app.
```
Android Debug Bridge version 1.0.41
Version 30.0.4-6686687
```

**Comment by AlexTCGPro** [comment]
Well. It's working now! Thanks.
Replacing the adb files and removing the -g did the trick

**Comment by sinichi19** [comment]
> Well. It's working now! Thanks.
> Replacing the adb files and removing the -g did the trick

Sir @AlexTCGPro  and @rom1v  requesting for your kind assistance where can i download the adb files? thank you

**Comment by Kalebesamuel** [comment]
423 / 5000
Resultados de tradução
In my case, the same error appeared.
I tried to run the .bat file in the same directory as my apk in debug mode, but the following error appeared:
INSTALL_CANCELED_BY_USER
So I enabled these options on my device, in developer options:
Install Via USB
USB debugging (Security settings)

I didn't run the .bat file again I just ran
npx react-native run-android with the device plugged in, and then it worked.

Redmi 9C
