### ISSUE TITLE
Suddenly closing on the last step

### ISSUE THREAD

**Issue by FrancoYamaDav** [rom1v/sndcpy#53]
OS: Windows 10
Xiaomi phone.
VLC installed on the pc.

On running the BAT file, it says "Press Enter once the audio is enabled" (or something like that). I give the app the permissions on my phone and when I press Enter the console suddenly closes.

Something I noticed is that on my phone there's a notification that reads  "sndcpy: Awaiting connection..." while all of this happens (it never dissapears).

Edit: It crashes no matter what key I press.

**Comment by FrancoYamaDav** [comment]
When I run as administrator.
The console says that it can´t find the "adb", meanwhile when I don´t run it as Admin it can find it.

**Comment by rom1v** [comment]
It fails to start VLC. Is VLC installed at the default location.

See #5

**Comment by FrancoYamaDav** [comment]
No it wasn´t and I didn´t realized that.

Thank you for the answer and sorry for the trouble!
