### ISSUE TITLE
A30s not connecting to command

### ISSUE THREAD

**Issue by Waffle1257** [rom1v/sndcpy#55]
My A30s have downloaded the app and my pc has downloaded the files too but everytime I allow sndcpy to record audio and cast it to my desktop it won't connect after I press enter in the cmd it is stuck in the "Press Enter once audio capture is authorized on the device to start playing..." command

**Comment by rom1v** [comment]
And when you press `Enter` in that terminal, what does it do? Is VLC correctly installed? (see #5)

**Comment by Waffle1257** [comment]
Oh I did not see that VLC was a requirement my bad

**Comment by Waffle1257** [comment]
I have downloaded VLC and it works perfectly fine now sorry for the inconvenience

**Comment by Astrokush** [comment]
since we have the same phone, i'd like to know what u did on your end
