### ISSUE TITLE
Set sound delay

### ISSUE THREAD

**Issue by subratami** [rom1v/sndcpy#57]
How can I set sound delay when iam using scrcpy.
There is some delay in sndcpy

**Comment by rom1v** [comment]
Set network-caching in the scripts (it's 0 on master, 50 on last release):

https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy#L29

https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L25

**Comment by subratami** [comment]
Thanks
