### ISSUE TITLE
Unable to play Audio, Issue with VLC

### ISSUE THREAD

**Issue by kphanipavan** [rom1v/sndcpy#58]
Hello,

I have been using SNDCPY for the last 6 months on Windows (10) and it worked flawlessly. Now I am on MacOS (10.15) now. When I press Enter, I see the VLC version and then it exits.

```bash
walle@Wall-Es-MacBook-Pro ~ % sndcpy
Waiting for device...
Performing Streamed Install
Success
28200
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...

VLC media player 3.0.11.1 Vetinari (revision 3.0.11.1-0-g52483f3ca2)
walle@Wall-Es-MacBook-Pro ~ % 
```
Am I pointing to the wrong VLC executable?
Added this to my PATH:  /Applications/VLC.app/Contents/MacOS
Or is there something else I should do? 
Thanks

**Comment by rom1v** [comment]
It seems to correctly start VLC (it prints `VLC media player 3.0.11.1 Vetinari (revision 3.0.11.1-0-g52483f3ca2)`).

Remove `-Idummy` from the `sndcpy` script, and open the messages dialog in VLC (Ctrl+m). Are there any errors?

**Comment by kphanipavan** [comment]
VLC didn't open automatically, I had to open it. There are no Errors and Warnings box is empty, Messages box is as shown below.
![Screenshot 2020-09-11 at 4 11 47 PM](https://user-images.githubusercontent.com/60005847/92914700-7fac2700-f449-11ea-97b5-12acd43a13b4.png)

**Comment by kphanipavan** [comment]
Hello, after a long time...

I have moved to linux. Haven't used it on my current setup because I have resorted to use Bluetooth A2DP instead, which I found to be easier to setup and working consistently.

I am closing this issue as I don't possess the Env on which this issue is based on.

Thank you for this, it was fun using this software. : ]
