### ISSUE TITLE
sndcpy: The system cannot find the path specified.

### ISSUE THREAD

**Issue by PlaceofYichen** [rom1v/sndcpy#60]
Hi there, thanks for the amazing work. 

I have countered an issue that: "sndcpy The system cannot find the path specified." I have adb installed; VLC installed. The android device works fine on scrcpy, too.
![sndcpy error](https://user-images.githubusercontent.com/50237753/93214608-64843480-f733-11ea-99c3-c6cf36b04e3b.png)

Thanks in advance for answering the question!

**Comment by rom1v** [comment]
What is the full path of your VLC?

See #5

**Comment by PlaceofYichen** [comment]
> What is the full path of your VLC?
> 
> See #5

Hiii. I installed VLC by the scoop command, and it's "D:\Scoop\apps\VLC\current\VLC.exe/" 

Am I supposed to move the sndcpy folder to the same directory?

**Comment by toihuynh95** [comment]
I have successfully followed the following steps:
Step 1: Check the path of VLC in sndcpy.bat file is correct or not? If not, update the correct path and save it. Usually they are installed at: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" or "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe".

Step 2: Then double click on the file `sndcpy.bat`. Continue to clicked on START NOW on phone, press Enter in the console to start playing on the computer. Good luck!

**Comment by PROTIKMNDL** [comment]
for me, if I execute sndcpy it doesn't transfer audio 
mobile app restart after I hit enter and cmd get closed

**Comment by dmigzz** [comment]
can it forward audio wirelessly or do i need to connect a cable ?

**Comment by rickvian** [comment]
it worked for me after i run the command prompt as administrator, and then cd to the sndcpy directory, run the sndcpy command,

**Comment by prakhar71** [comment]
Very Simple Fix !! 
Step 1 : delete old Vlc player 
Step 2 : install latest version of vlc and install it in C:/program files
step 3 : open cmd admin(Administrator mode only)
Step 4 : navigate to the dir. where sndcpy.bat is stored 
step 5 : Run sndcpy.bat
