### ISSUE TITLE
APP EXCEMPTIONS

### ISSUE THREAD

**Issue by diazraymond026** [rom1v/sndcpy#62]
Hi, is there any way to fix the internal audio of call of duty mobile, on youtube sndcpy runs smoothly but on codm doesn't work.

**Comment by rom1v** [comment]
AFAIK, only the developers of the app are able to do something to authorize audio capture.

**Comment by FerLuisxd** [comment]
There are some exceptions guys, CODM MUST allow to mirror audio explicitly, apps <Android10  have it off by default but apps>=Android10 have it on by default. So it is really up to them

**Comment by abasgames** [comment]
Yes you can you must enable audio debugging see https://source.android.com/devices/audio/debugging?authuser=1
