### ISSUE TITLE
" Error: Unknown option: -g "  and  " Error type 3 "

### ISSUE THREAD

**Issue by ptrsstory** [rom1v/sndcpy#72]
Waiting for device...
Performing Push Install
sndcpy.apk: 1 file pushed, 0 skipped. 25.1 MB/s (91689 bytes in 0.003s)
Error: Unknown option: -g
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Error type 3
Error: Activity class {com.rom1v.sndcpy/com.rom1v.sndcpy.MainActivity} does not exist.
Press Enter once audio capture is authorized on the device to start playing...
Playing audio...

I need help pls

**Comment by ptrsstory** [comment]
The audio does not work.

**Comment by rom1v** [comment]
> Error: Unknown option: -g

Which version of `adb` do you use?

As a workaround, remove `-g` here: https://github.com/rom1v/sndcpy/blob/f0995ca4d0002ef288c74c70d4c0eb48354449d5/sndcpy.bat#L15

**Comment by ptrsstory** [comment]
I dont know how to check the adb but my phone is oppo f1s.

**Comment by ptrsstory** [comment]
When i remove the -g, it says Failure [INSTALL_FAILED_OLDER_SDK].

**Comment by ptrsstory** [comment]
Thanks btw for your response.

**Comment by rom1v** [comment]
Sndcpy requires Android 10.
