### ISSUE TITLE
Failed to install sndcpy.apk

### ISSUE THREAD

**Issue by hecc01** [rom1v/sndcpy#77]
So I tried to run sndcpy, but i was hit with this:

Waiting for device...
Performing Streamed Install
adb: failed to install sndcpy.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:542)
        at com.android.server.pm.PackageInstallerService.createSession(PackageUninstalling existing version first...
Failure [DELETE_FAILED_INTERNAL_ERROR]
Failed with error #1.
Press any key to continue . . .

I dont know what permission thats talking about, so in developer options on my phone i turned on every option that has something related to installing apps via USB, but it still doesnt work.

Whats wrong here?

**Comment by hecc01** [comment]
i also tried to install sndcpy.apk manually by doing it on my phone but it says somethings wrong and the app is not installed

**Comment by rom1v** [comment]
See #39.

**Comment by hecc01** [comment]
i did what you said... but now its just stuck on waiting for device. its been like this for a while now too

**Comment by hecc01** [comment]
i tried again and now its stuck at 

Waiting for device...
* daemon not running; starting now at tcp:5037
* daemon started successfully

**Comment by rom1v** [comment]
Your device is not just detected by adb. Check `adb devices`.

**Comment by hecc01** [comment]
ah ok, got it to work. thanks for your help!

**Comment by vish0172** [comment]
I am having the same issue
can you help me solve this
![sndcpy_issue](https://github.com/rom1v/sndcpy/assets/141177877/f8b8736c-d577-4ce2-8560-6013ac792145)
