### ISSUE TITLE
how can i control my sound in vlc

### ISSUE THREAD

**Issue by Apurikotto** [rom1v/sndcpy#78]
vlc default sound is too big,i tried to reduce my system sound，but my viewer said its too small, can i control vlc sound？
thank you very much.

**Comment by VincentChui2005** [comment]
After having the sndcpy on, you can press Windows + R and type "sndcpy" inside to open a volume control panel
Then, change the volume of the VLC player to whatever you want as appropriate

**Comment by Apurikotto** [comment]
> After having the sndcpy on, you can press Windows + R and type "sndcpy" inside to open a volume control panel
> Then, change the volume of the VLC player to whatever you want as appropriate

thank you sir,but when i type sndcpy in win+r ,it said "sndcpy "cant find, please type the correct name and try it again.
i dont know what is it correct said in english,beacuse my system is japanese. i upload the screenshot
anyway, thank you so much sir.
![06](https://user-images.githubusercontent.com/72537772/100435284-a1569b00-3095-11eb-859c-d6af30b732c0.png)

**Comment by rom1v** [comment]
<kbd>Win</kbd>+<kbd>r</kbd>, `cmd.exe`, and this opens a terminal, where you go to the sndcpy folder `cd C:\.......`, and type `sndcpy`.

**Comment by Apurikotto** [comment]
> Win+r, `cmd.exe`, and this opens a terminal, where you go to the sndcpy folder `cd C:\.......`, and type `sndcpy`.

thank you sir , but nothing happend,it is the same when i use cmd to open the sndcpy or i use sndcpy.bat.
i missed something or i did something wrong?
![1](https://user-images.githubusercontent.com/72537772/100436766-b46a6a80-3097-11eb-86cc-30bcc2ac0bcf.png)

**Comment by rom1v** [comment]
Try to play Youtube or start a video on VLC Android. Does it work?

**Comment by Apurikotto** [comment]
> Try to play Youtube or start a video on VLC Android. Does it work?

i can hear the sound in my pc, but i cant control the volume 
![48](https://user-images.githubusercontent.com/72537772/100437778-298a6f80-3099-11eb-8ec5-c07dcd759c66.png)
i mean i only can control the sound in here 
![51](https://user-images.githubusercontent.com/72537772/100438075-9aca2280-3099-11eb-9c28-0d0b4510eece.png)
thank you sir.

**Comment by rom1v** [comment]
The device volume and computer volume are independent.

You can mute the device and set the volume to max on the computer… or the opposite…

**Comment by Apurikotto** [comment]
> The device volume and computer volume are independent.
> 
> You can mute the device and set the volume to max on the computer… or the opposite…

so there is no way to control the volume in vlc pc ?only can control system volume ?
i cant find a blance to get the sound.
or my volume is too big,my viewer can hear it ,but i cant bear it.
or my volume is good, my viewer cant hear.
or i need to change a new earphone better?
anyway, thank you so much to listen my sooooo bad english.
thank you sir.
