### ISSUE TITLE
Success in connection but audio not playing in pc

### ISSUE THREAD

**Issue by surya-cn** [rom1v/sndcpy#89]
I had issue in connection..then i edited bat file because my vlc player was installed in program files x86 folder..
So i changed path file..when i ran bat file it shows to press enter and Playing audio but I can't hear in pc..audio is only in Mobile...help

**Comment by rom1v** [comment]
On Android, try with VLC for Android or Youtube. Does it work?

**Comment by surya-cn** [comment]
> On Android, try with VLC for Android or Youtube. Does it work?

I've vlc player in both pc and mobile..still it not working

**Comment by rom1v** [comment]
It should work if you play a video in VLC Android or in Youtube. If it does not, your device does noy implement the API properly.

**Comment by surya-cn** [comment]
Ok so now its working but when i try to record using obs... audio is not captured..if i turn off it comes back..but there's delay in audio

**Comment by surya-cn** [comment]
Obs record issue..audio is quite getting delay..and if i try to record my gameplay using obs..audio is closed..and when i close obs..audio comes back..what i can do to record gameplay with sound
