### ISSUE TITLE
OBS issue

### ISSUE THREAD

**Issue by surya-cn** [rom1v/sndcpy#90]
I opened both sndcpy and scrcpy...it works fine..even though there's audio delay...but when i open obs to record gameplay...audio is off...and if i close obs..audio comes back...what to do if i need to window capture with audio

**Comment by msyagami** [comment]
what Android version and OBS version are you using? and was there logs on the command prompt during the record? mine seems to work.

**Comment by neutronsgit** [comment]
Same Problem here, with Android 10 and OBS 26.0.2. I haven't noticed something in the command prompt. But it seems to work if you start OBS first, and then you start sndcpy.
