### ISSUE TITLE
System couldn't find the specified path

### ISSUE THREAD

**Issue by NancokPS2** [rom1v/sndcpy#94]
It all works flawlessly until the "Playing audio..." message appears, then i get "System couldn't find the specified path", VLC doesn't seem to open on the background either, any help?
Edit: the error has been fixed (i changed the path since my HDD is Y, not C), but the audio still keeps coming off the phone and ignores my PC

**Comment by rom1v** [comment]
> the audio still keeps coming off the phone and ignores my PC

Also with Youtube or VLC for Android?

**Comment by NancokPS2** [comment]
> > the audio still keeps coming off the phone and ignores my PC
> 
> Also with Youtube or VLC for Android?

I didn't knew i needed VLC for android, it does seem to work with VLC but ONLY with VLC, any other apps and even phone notifications still come trough the phone

**Comment by rom1v** [comment]
No you don't need it, but it is known to not prevent audio capture, so it's a good test.

Not all apps authorize audio capture: https://github.com/rom1v/sndcpy#apps-restrictions

**Comment by NancokPS2** [comment]
Oooh, that could explain it, i guess that i'm just unlucky most of my apps don't allow it, i found a streaming app that can do it trough LAN with all audio, not as efficient but i guess it'll do
The name's IP Webcam, should anyone with this issue stumble upon this comment

**Comment by rom1v** [comment]
Apps which can record audio from all the apps (or before Android 10) just record via the microphone.
