### ISSUE TITLE
Add argument to not install apk?

### ISSUE THREAD

**Issue by bayazidbh** [rom1v/sndcpy#96]
Sorry, I don't exactly know how sndcpy works under the hood, but would it be possible to add an argument to skip checking/installing apk? I believe once the apk is installed it remains installed on the phone, yes? While I do agree with the implementation of checking and automatically installing apk in the default running option, would it be possible to add an option to just immediately go to the ENTER part of the process?

If it's not possible or hard to implement then that is fine, I am thankful for the ability to forward audio via usb cable on Android 10, but I feel that it would be nice to make it more automated.

**Comment by rom1v** [comment]
It does not install it if it's not necessary (it has to check, but it's very quick, around 20ms IIRC).
